#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Parallel Programming in Futhark documentation build configuration file, created by
# sphinx-quickstart on Sun Dec  3 10:44:29 2017.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys
sys.path.insert(0, os.path.abspath('.'))

from pygments.lexer import RegexLexer
from pygments import token
from sphinx.highlighting import lexers


# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = ['sphinx.ext.mathjax',
              'sphinxcontrib.bibtex']

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = 'Parallel Programming in Futhark'
copyright = '2018 Martin Elsman, Troels Henriksen, and Cosmin E. Oancea'
author = 'Martin Elsman, Troels Henriksen, and Cosmin E. Oancea'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = '0.80'
# The full version, including alpha/beta/rc tags.
release = '0.80'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

class FutharkLexer(RegexLexer):
    name = 'Futhark'

    tokens = {
        'root': [
            (r'(if|then|else|let|loop|in|default|val|for|do|with|local|open|include|import|type|entry|module|empty|while|unsafe)\b', token.Keyword),
            (r"[a-zA-Z_][a-zA-Z0-9_']*", token.Name),
            (r"-- .*", token.Comment),
            (r'.', token.Text)
        ]
    }

lexers['futhark'] = FutharkLexer()

highlight_language = 'futhark'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'futhark'
html_theme_path = ['_theme']

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
html_theme_options = {}

html_logo = '_static/futhark-logo-small.png'
html_title = 'Parallel Programming in Futhark'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# This is required for the alabaster theme
# refs: http://alabaster.readthedocs.io/en/latest/installation.html#sidebars
html_sidebars = { '**': ['globaltoc.html', 'relations.html', 'sourcelink.html', 'searchbox.html'], }


# -- Options for HTMLHelp output ------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'ParallelProgramminginFutharkdoc'


# -- Options for LaTeX output ---------------------------------------------

latex_logo = '_static/futhark-logo-small.png'

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    'papersize': 'letterpaper',
    #'papersize': 'b5paper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    'pointsize': '12pt',
    'fncychap': '\\usepackage[Lenny]{fncychap}', # Bjarne, Lenny, Glenn, Sonny, Conny, Rejne
    # Additional stuff for the LaTeX preamble.
    #
    'preamble': '\\input{../../_templates/layout.tex}',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
    'sphinxsetup': 'TitleColor={rgb}{0,0,0},noteborder=2px,noteBorderColor={rgb}{0,0,0}',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
  (master_doc,
   'root.tex',
   'Parallel Programming in Futhark',
   '\\large Martin Elsman \\and \\large Troels Henriksen \\and \\large Cosmin E. Oancea',
   'manual',
   False)
]


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'parallelprogramminginfuthark', 'Parallel Programming in Futhark Documentation',
     [author], 1)
]


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'ParallelProgramminginFuthark', 'Parallel Programming in Futhark Documentation',
     author, 'ParallelProgramminginFuthark', 'One line description of project.',
     'Miscellaneous'),
]

# -- Final setup --

def setup(app):
    app.add_javascript('exercises.js')
